Clarify types and requirements levels for the plate/well specification
ome/ngff pull request #126
Opened 2022-05-26 20:50 UTC by sbesson

This commit rewrites the section and ensures that:

- each key has a requirement level specified as MUST/SHOULD/MAY
- the type for the value of each key is explicitly defined

The requirements & types should match the JSON schemas introduced in #120

2022-05-26 23:38 UTC, melissalinkert requested changes
Super pedantic comments aside (some of which are things not introduced by this PR), this does read better than before.

2022-05-26 23:38 UTC, melissalinkert commented on 0.4/index.bs
> +acquisition object MUST contain an `id` key whose value MUST be an unique integer identifier
`a unique integer identifier greater than or equal to 0`?

2022-05-26 23:38 UTC, melissalinkert commented on 0.4/index.bs
> +acquisition. Each acquisition object MAY contain a `description` key whose value MUST be a
Is it expected that `description` isn't in the plate JSON schema?

2022-05-26 23:38 UTC, melissalinkert commented on 0.4/index.bs
> +key whose value MUST be an integer indicating the maximum number of fields of view for the
`an integer greater than 0`?

2022-05-26 23:38 UTC, melissalinkert commented on 0.4/index.bs
> +a `startime` and/or `endtime` key whose values MUST be integer epoch timestamps specifying
`starttime`

2022-05-26 23:38 UTC, melissalinkert commented on 0.4/index.bs
> +defining the columns of the plate. Each column object object defines the properties of
`column object defines`

2022-05-26 23:38 UTC, melissalinkert commented on 0.4/index.bs
> +contain a `name` key whole value is a string specifying the column name. The `name` MUST
`whose value`

2022-05-26 23:38 UTC, melissalinkert commented on 0.4/index.bs
> +The `plate` dictionary SHOULD contain a `field_count` key whose value MUST be an integer
`an integer greater than 0`?

2022-05-26 23:38 UTC, melissalinkert commented on 0.4/index.bs
> +defining the rows of the plate. Each row object object defines the properties of
`row object defines`

2022-05-26 23:38 UTC, melissalinkert commented on 0.4/index.bs
> +`path` key whose value MUST be a string specifying the path to the field of view. If multiple
Add something like ```The `path` MUST
contain only alphanumeric characters, MUST be case-sensitive, and MUST NOT be a duplicate of any
other `path` in the `images` list.```, similar to row and column names above?

2022-05-26 23:38 UTC, melissalinkert commented on 0.4/index.bs
> +MUST be an integer identifying the acquisition which MUST match one of acquisition JSON
`one of the`

2022-05-27 11:35 UTC, sbesson commented
Thanks for the thorough review @melissalinkert. Pedantic comments are very useful. The aim of this PR is to reduce the ambiguity in the definition of these specifications. Pushed a few commits addressing your suggestions and adding the acquisition description to the JSON schema.

I also ported the same text to the `latest` specification to save myself another PR once this is merged. If additional changes are requested, I'll apply them to both specifications.

2022-05-27 15:17 UTC, melissalinkert approved these changes
Just a couple of typos left, :+1: once those are fixed.

2022-05-27 15:17 UTC, melissalinkert commented on 0.4/index.bs
> +greater than of equal to 0 within the context of the plate to which fields of view can refer
`or equal to`

2022-05-27 15:17 UTC, melissalinkert commented on latest/index.bs
> +greater than of equal to 0 within the context of the plate to which fields of view can refer
`or equal to`

2022-05-27 15:17 UTC, melissalinkert commented on latest/index.bs
> +version of the plate specificaton.
`specification` (as fixed above)

2022-05-30 07:46 UTC, merged