Add missing plate and well schemas for 0.1, 0.2, 0.3
ome/ngff pull request #127
Opened 2022-05-27 09:43 UTC by will-moore

As discussed in https://github.com/ome/ome-ngff-validator/pull/3, we can't validate HCS data for v 0.1, 0.2, 0.3 because of missing schemas.

This adds plate schema for 0.2 & 0.3 (copying over the 0.1 schema and updating version)
and adds well schema for 0.1, 0.2, 0.3 (copying the 0.4 schema). This only requires 'path' attribute which is correct for all versions.

cc @sbesson

2022-05-29 20:15 UTC, sbesson requested changes
A few comments based on manual comparison with  https://github.com/ome/ngff/blob/main/0.4/schemas/plate.schema and https://github.com/ome/ngff/blob/main/0.4/schemas/well.schema.

Ideally, it would be useful to have a JSON test suite for each version/specification with minimally a compliant example so that we can test the validation logic works.

2022-05-29 20:15 UTC, sbesson commented on 0.2/schemas/well.schema
> +  "$id": "https://ngff.openmicroscopy.org/0.4/schemas/well.schema",
```suggestion
  "$id": "https://ngff.openmicroscopy.org/0.2/schemas/well.schema",
```

2022-05-29 20:15 UTC, sbesson commented on 0.3/schemas/plate.schema
> +  "$id": "http://localhost:8000/plate.schema",
```suggestion
  "$id": "https://ngff.openmicroscopy.org/0.3/schemas/plate.schema"
```

2022-05-29 20:15 UTC, sbesson commented on 0.3/schemas/well.schema
> +  "$id": "https://ngff.openmicroscopy.org/0.4/schemas/well.schema",
```suggestion
  "$id": "https://ngff.openmicroscopy.org/0.3/schemas/well.schema",
```

2022-05-29 20:15 UTC, sbesson commented on 0.2/schemas/plate.schema
> +  "$id": "http://localhost:8000/plate.schema",
```suggestion
  "$id": "https://ngff.openmicroscopy.org/0.2/schemas/plate.schema",
```

2022-05-29 20:15 UTC, sbesson commented on 0.2/schemas/plate.schema
> +  "title": "NGFF Plate",
```suggestion
  "title": "OME-NGFF plate schema",
```

2022-05-29 20:15 UTC, sbesson commented on 0.2/schemas/plate.schema
> +                "type": "number"
Specified as `integer` in 0.4/latest schemas

2022-05-29 20:15 UTC, sbesson commented on 0.2/schemas/plate.schema
> +                "type": "number"
Specified as `integer` in 0.4/latest schemas

2022-05-29 20:15 UTC, sbesson commented on 0.2/schemas/plate.schema
> +                "type": "number"
Specified as `integer` in 0.4/latest schemas

2022-05-29 20:15 UTC, sbesson commented on 0.2/schemas/plate.schema
> +              "starttime": {
Should we also have `endttime`?

2022-05-29 20:15 UTC, sbesson commented on 0.3/schemas/plate.schema
> +                "type": "number"
Same as above

2022-05-29 20:15 UTC, sbesson commented on 0.3/schemas/plate.schema
> +                "type": "number"
Same as above

2022-05-29 20:15 UTC, sbesson commented on 0.3/schemas/plate.schema
> +                "type": "number"
Same as above

2022-05-30 08:49 UTC, will-moore commented
@sbesson Thanks for the fixes etc. I think the other issues are fixed in [09ab485](https://github.com/ome/ngff/pull/127/commits/09ab485d2869fbae8e3346f0694b399613e79b9e)

2022-05-30 08:49 UTC, will-moore commented
I'll add tests...

2022-05-30 12:27 UTC, will-moore commented
"feels like an overhead for the scope of this work" -> you think it should be done in this PR, or it outside the scope of this PR?
Pushed fix to 0.1 plate.schema.

2022-05-30 12:30 UTC, sbesson approved these changes

2022-05-30 12:30 UTC, merged

2022-05-30 12:31 UTC, sbesson commented
> you think it should be done in this PR, or it outside the scope of this PR?

Not worth it imo unless we start adding more content to these old versions schemas.

2022-05-30 17:49 UTC, will-moore commented
I'm missing something. Having merged this, I'd expect https://github.com/ome/ngff/tree/main/0.3/schemas to show plate.schema but I don't see it there??

2022-05-30 20:27 UTC, sbesson commented
@joshmoore would this be related to the afternoon force push events?